#!/usr/bin/env bash
#
# BSSG - Site Initialization Script
# Initializes a new, separate site directory structure.
#

set -e

# Terminal colors (copied for standalone use if needed, but should be sourced)
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# --- Configuration ---
# Get the directory where BSSG core scripts are located
BSSG_CORE_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
CORE_CONFIG_LOCAL="$BSSG_CORE_DIR/config.sh.local"

# --- Argument Validation ---
TARGET_DIR="$1"
if [ -z "$TARGET_DIR" ]; then
    echo -e "${RED}Error: Target directory argument is required.${NC}"
    echo -e "Usage: ./bssg.sh init <target_directory>"
    exit 1
fi

echo -e "${YELLOW}Initializing new BSSG site structure based on input '$TARGET_DIR'...${NC}"

# --- Expand Tilde for Internal Operations ---
TARGET_DIR_EXPANDED="$TARGET_DIR"
if [[ "$TARGET_DIR" == "~" ]]; then
    TARGET_DIR_EXPANDED="$HOME"
elif [[ "$TARGET_DIR" == "~/"* ]]; then
    TARGET_DIR_EXPANDED="$HOME/${TARGET_DIR#\~/}"
fi
echo "Path expanded for internal operations: '$TARGET_DIR_EXPANDED'"

# Ensure target directory exists using the expanded path
# Use -p to avoid errors if it already exists
mkdir -p "$TARGET_DIR_EXPANDED" || { echo -e "${RED}Error: Failed to create directory '$TARGET_DIR_EXPANDED'${NC}"; exit 1; }

# Get absolute path for the target directory using the expanded path
# Check if cd was successful before proceeding
if ! cd "$TARGET_DIR_EXPANDED"; then
    echo -e "${RED}Error: Failed to change directory to '$TARGET_DIR_EXPANDED'${NC}" >&2
    exit 1
fi
TARGET_ABS_PATH=$(pwd)
# Go back to original directory (important if BSSG core config needs modification later)
cd - > /dev/null
echo "Target directory resolved to absolute path: $TARGET_ABS_PATH"

# Create subdirectories using the *expanded* path for reliability
echo "Creating subdirectories within '$TARGET_ABS_PATH'..."
mkdir -p "$TARGET_ABS_PATH/src"
mkdir -p "$TARGET_ABS_PATH/pages"
mkdir -p "$TARGET_ABS_PATH/drafts"
mkdir -p "$TARGET_ABS_PATH/drafts/pages" # Subdir for page drafts
mkdir -p "$TARGET_ABS_PATH/static"
mkdir -p "$TARGET_ABS_PATH/output" # Define output dir for the site
echo -e "${GREEN}Directory structure created successfully.${NC}"

# --- Site Config Generation ---
# Use absolute path to reliably create the config file itself
SITE_CONFIG_LOCAL="$TARGET_ABS_PATH/config.sh.local"
echo "Generating site-specific config file: $SITE_CONFIG_LOCAL"

# Create config content using the *original* user-provided path format ($TARGET_DIR)
# Note: Paths inside might be relative (e.g., ~/src) or absolute
# We DO NOT define TEMPLATES_DIR or THEMES_DIR, allowing them to be sourced
# from the core config.sh (or its core config.sh.local override).
cat > "$SITE_CONFIG_LOCAL" << EOF
#!/usr/bin/env bash
#
# Local configuration for BSSG site created from input: '$TARGET_DIR'
# Resolved absolute path: $TARGET_ABS_PATH
# Generated by: bssg init
#
# Refer to the main 'config.sh' file in your BSSG installation
# for a complete list of available configuration options.
#

# --- Content Directories (Using path format provided during init: '$TARGET_DIR') ---
# Note: Tilde (~) expansion will occur when this file is sourced by the shell.
SRC_DIR="$TARGET_DIR/src"
PAGES_DIR="$TARGET_DIR/pages"
DRAFTS_DIR="$TARGET_DIR/drafts"
STATIC_DIR="$TARGET_DIR/static"
OUTPUT_DIR="$TARGET_DIR/output" # Site output directory

# --- Build Specific Overrides ---
# Place the cache directory within this site's directory
CACHE_DIR="$TARGET_DIR/.bssg_cache"

# --- Site Specific Overrides (Examples) ---
# SITE_TITLE="My New Site"
# SITE_URL="http://example.com"
# THEME="dark" # Optional: override theme just for this site

EOF

echo -e "${GREEN}Site config '$SITE_CONFIG_LOCAL' created.${NC}"

# --- Core Config Sourcing (Optional) ---
echo
echo -e "${YELLOW}Optional: Automatically load this site's config?${NC}"
echo "This will modify '$CORE_CONFIG_LOCAL' in your BSSG installation directory."
echo "It will add a line to source '$SITE_CONFIG_LOCAL' whenever you run ./bssg.sh from the core directory."
echo "This avoids needing to specify '--config $SITE_CONFIG_LOCAL' for every build."

# Ask for confirmation, defaulting to Yes
read -p "Modify '$CORE_CONFIG_LOCAL' to source the new site config? [Y/n]: " confirm </dev/tty

# Default to 'yes' if user just presses Enter
confirm=${confirm:-Y}

if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
    echo "Modifying core config: $CORE_CONFIG_LOCAL"

    # Create the core config.sh.local if it doesn't exist
    if [ ! -f "$CORE_CONFIG_LOCAL" ]; then
        echo "#!/usr/bin/env bash" > "$CORE_CONFIG_LOCAL"
        echo "# BSSG Core Local Configuration Overrides" >> "$CORE_CONFIG_LOCAL"
        echo "Created $CORE_CONFIG_LOCAL."
    fi

    # Check if the source line already exists
    if grep -Fxq "source \"$SITE_CONFIG_LOCAL\"" "$CORE_CONFIG_LOCAL"; then
        echo "Source line already exists in $CORE_CONFIG_LOCAL. No changes needed."
    else
        # Append the source line
        echo "" >> "$CORE_CONFIG_LOCAL" # Add a newline for separation
        echo "# Source site-specific config for: $TARGET_ABS_PATH" >> "$CORE_CONFIG_LOCAL"
        echo "source \"$SITE_CONFIG_LOCAL\"" >> "$CORE_CONFIG_LOCAL"
        echo -e "${GREEN}Successfully added source line to $CORE_CONFIG_LOCAL.${NC}"
    fi
else
    echo "Skipping modification of core config."
    echo "To use this site, run BSSG commands with the --config flag or set BSSG_LCONF environment variable:"
    echo "  ./bssg.sh build --config $SITE_CONFIG_LOCAL"
    echo "  export BSSG_LCONF=\"$SITE_CONFIG_LOCAL\" && ./bssg.sh build"
fi

echo
echo -e "${GREEN}Site initialization complete in '$TARGET_ABS_PATH'.${NC}"
